"""Real PostgreSQL checks use only temporary tables and roll everything back."""

import importlib.util
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

import pytest
from argon2 import PasswordHasher
from cryptography.fernet import Fernet
from sqlalchemy import text

import planting_database as planting
from mangrovision_db import like_appointments as service
from mangrovision_db import appointment_email as delivery
from mangrovision_db.compat import CompatConnection, get_engine

pytestmark = pytest.mark.skipif(os.getenv('MANGROVISION_RUN_TEMP_LIKE_TESTS') != '1', reason='Temporary PostgreSQL checks are opt-in.')


@pytest.fixture()
def workspace(monkeypatch):
    try:
        connection = get_engine().connect()
    except Exception as issue:
        raise pytest.fail.Exception(f'Isolated database check could not connect ({type(issue).__name__}); connection details suppressed.', pytrace=False) from None
    transaction = connection.begin()
    try:
        connection.exec_driver_sql("""
            SET LOCAL statement_timeout = '20s';
            SET LOCAL search_path = pg_temp, public;
            CREATE TEMP TABLE users(id BIGINT PRIMARY KEY, role TEXT);
            INSERT INTO users VALUES (1, 'lgu'), (2, 'viewer');
            CREATE TEMP TABLE staff_notifications (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, event_key TEXT,
                kind TEXT, title TEXT, body TEXT, target_path TEXT, read_at TIMESTAMPTZ,
                UNIQUE (user_id, event_key)
            );
            CREATE TEMP TABLE organizations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
                normalized_name TEXT UNIQUE NOT NULL, inspection_interval_days INTEGER NOT NULL,
                created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ
            );
            CREATE TEMP TABLE site_zones(id BIGINT PRIMARY KEY, name TEXT, polygon_geojson JSONB);
            CREATE TEMP TABLE planters (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, full_name TEXT,
                organization_id BIGINT, username TEXT UNIQUE, password_hash TEXT, phone TEXT,
                base_label TEXT, base_lat DOUBLE PRECISION, base_lon DOUBLE PRECISION, notes TEXT,
                status TEXT DEFAULT 'active', participant_count INTEGER DEFAULT 1, merged_into_planter_id BIGINT
            );
            CREATE TEMP TABLE organization_participants(planter_id BIGINT, slot INTEGER, device_key_hash TEXT);
            CREATE TEMP TABLE planter_assignments(id BIGINT, planter_id BIGINT);
            CREATE TEMP TABLE planter_assignment_points(id BIGINT, assignment_id BIGINT,
                released_at TIMESTAMPTZ, sequence_num INTEGER, participant_slot INTEGER);
            CREATE TEMP TABLE planting_schedules (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_site_id BIGINT, organization TEXT NOT NULL, organization_id BIGINT,
                inspection_interval_days INTEGER, contact TEXT, title TEXT NOT NULL,
                start_at TIMESTAMPTZ NOT NULL, end_at TIMESTAMPTZ NOT NULL CHECK (end_at > start_at),
                expected_planters INTEGER, expected_seedlings INTEGER, status TEXT NOT NULL DEFAULT 'requested',
                notes TEXT, created_by_user_id BIGINT, updated_by_user_id BIGINT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ
            );
        """)
        for name in ('20261006_0013_like_appointments.py', '20261007_0014_like_appointment_delivery.py'):
            spec = importlib.util.spec_from_file_location('like_migration', Path(__file__).resolve().parents[1] / 'alembic/versions' / name)
            migration = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(migration)
            statements = []
            monkeypatch.setattr(migration.op, 'execute', statements.append)
            migration.upgrade()
            for statement in statements:
                # Only session-local objects are created or changed. Never migrate live tables.
                statement = statement.replace('mangrovision.', 'pg_temp.').replace('CREATE TABLE pg_temp.', 'CREATE TEMP TABLE pg_temp.')
                connection.exec_driver_sql(statement)

        class TempConnection(CompatConnection):
            def __init__(self):
                super().__init__(connection)
                self.savepoint = connection.begin_nested()
            def commit(self):
                self.savepoint.commit()
            def rollback(self):
                if self.savepoint.is_active:
                    self.savepoint.rollback()
            def close(self):
                self.rollback()

        monkeypatch.setattr(planting, '_get_connection', TempConnection)
        monkeypatch.setattr(delivery, 'get_connection', TempConnection)
        monkeypatch.setattr(planting, 'append_activity', lambda *args, **kwargs: None)
        monkeypatch.setenv('LIKE_EMAIL_ENCRYPTION_KEY', Fernet.generate_key().decode())
        monkeypatch.setenv('MANGROVISION_PUBLIC_URL', 'https://example.org')
        yield connection
    finally:
        transaction.rollback()
        connection.close()


def values(**changes):
    start = (datetime.now(timezone.utc) + timedelta(days=3)).replace(hour=0, minute=0, second=0, microsecond=0)
    body = dict(submission_key=uuid4(), organization='Example community', contact_name='Test coordinator',
                phone='09123456789', email='test@example.org', title='Community planting',
                appointment_type='tree_planting',
                start_at=start, end_at=start + timedelta(hours=2), participants=20,
                notes='For test only', consent=True, website='')
    return {**body, **changes}


def request_id(connection):
    return connection.execute(text('SELECT id FROM like_appointment_requests ORDER BY id DESC LIMIT 1')).scalar_one()


def test_request_is_private_and_does_not_register_an_organization(workspace):
    result = service.submit_appointment(values(), 'test-peer')
    assert set(result) == {'reference', 'status', 'timezone'}
    assert result['reference'].startswith('LIKE-')
    assert workspace.execute(text('SELECT count(*) FROM organizations')).scalar() == 0
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 0
    private = service.list_appointments()[0]
    assert private['phone'] == '09123456789'
    assert 'submission_key' not in private and 'payload_hash' not in private


def test_submit_retries_once_and_rejects_changed_payload(workspace):
    body = values()
    first = service.submit_appointment(body, 'test-peer')
    assert service.submit_appointment(body, 'test-peer') == first
    with pytest.raises(service.AppointmentConflict):
        service.submit_appointment({**body, 'participants': 21}, 'test-peer')
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 1


def test_confirmation_is_atomic_and_idempotent(workspace):
    body = values()
    service.submit_appointment(body, 'test-peer')
    review = {'action': 'confirmed', 'contacted': True, 'start_at': body['start_at'] + timedelta(hours=1), 'end_at': body['end_at'] + timedelta(hours=1)}
    first = service.review_appointment(request_id(workspace), review, 1)
    assert service.review_appointment(first['id'], review, 1)['schedule_id'] == first['schedule_id']
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 1
    schedule = planting.get_planting_schedule(first['schedule_id'])
    assert schedule['source'] == 'website' and schedule['status'] == 'confirmed'
    assert schedule['start_time'] == '09:00' and schedule['inspection_interval_days'] == 14
    assert workspace.execute(text('SELECT count(*) FROM organizations')).scalar() == 1
    assert workspace.execute(text('SELECT count(*) FROM planters')).scalar() == 1
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_emails')).scalar() == 1
    assert workspace.execute(text('SELECT contacted FROM like_appointment_requests')).scalar() is True


def test_confirmation_requires_contact_and_failed_approval_leaves_no_schedule(workspace, monkeypatch):
    service.submit_appointment(values(), 'test-peer')
    with pytest.raises(ValueError, match='Contact the requester'):
        service.review_appointment(request_id(workspace), {'action': 'confirmed'}, 1)
    original = planting.create_planting_schedule
    def fail_after_insert(**kwargs):
        original(**kwargs)
        raise RuntimeError('Simulated failure after schedule insertion')
    monkeypatch.setattr(planting, 'create_planting_schedule', fail_after_insert)
    with pytest.raises(RuntimeError):
        service.review_appointment(request_id(workspace), {'action': 'confirmed', 'contacted': True}, 1)
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 0
    assert workspace.execute(text('SELECT count(*) FROM organizations')).scalar() == 0
    assert workspace.execute(text('SELECT status FROM like_appointment_requests')).scalar() == 'pending'


@pytest.mark.parametrize('action', ['declined', 'cancelled'])
def test_decline_and_cancel_require_reason_and_create_no_schedule(workspace, action):
    service.submit_appointment(values(), 'test-peer')
    with pytest.raises(ValueError, match='reason'):
        service.review_appointment(request_id(workspace), {'action': action}, 1)
    reviewed = service.review_appointment(request_id(workspace), {'action': action, 'decision_notes': 'Agreed another activity instead.'}, 1)
    assert reviewed['status'] == action
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 0


def test_rate_limit_preserves_successful_requests_and_retry_receipt(workspace):
    first = values()
    receipt = service.submit_appointment(first, 'test-peer')
    for _ in range(4):
        service.submit_appointment(values(), 'test-peer')
    with pytest.raises(service.AppointmentRateLimit):
        service.submit_appointment(values(), 'test-peer')
    assert service.submit_appointment(first, 'test-peer') == receipt
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 5


def test_manual_schedule_creation_still_works(workspace):
    body = values()
    schedule = planting.create_planting_schedule(organization=body['organization'], inspection_interval_days=14,
        title='Staff-assisted planting', start_at=body['start_at'], end_at=body['end_at'], created_by_user_id=1)
    assert schedule['source'] == 'staff' and schedule['status'] == 'requested'
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 0


def test_client_database_roles_cannot_access_request_tables(workspace):
    roles = workspace.execute(text("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")).scalars().all()
    for role in roles:
        for table in ('like_appointment_requests', 'like_appointment_rate_limits', 'like_appointment_emails'):
            for privilege in ('SELECT', 'INSERT', 'UPDATE', 'DELETE'):
                assert workspace.execute(text('SELECT has_table_privilege(:role, :table, :privilege)'),
                    {'role': role, 'table': f'pg_temp.{table}', 'privilege': privilege}).scalar() is False


def test_all_pending_requests_remain_visible_beyond_history_limit(workspace):
    workspace.exec_driver_sql("""
        INSERT INTO like_appointment_requests
            (reference, submission_key, payload_hash, organization, contact_name, phone,
             title, start_at, end_at, participants, status)
        SELECT 'LIKE-QUEUE-' || n, md5('queue-' || n)::uuid, 'test-hash', 'Test group',
            'Test coordinator', '09123456789', 'Test planting', CURRENT_TIMESTAMP + INTERVAL '1 day',
            CURRENT_TIMESTAMP + INTERVAL '1 day 2 hours', 20, 'pending'
        FROM generate_series(1, 201) n;
    """)
    assert len(service.list_appointments()) == 201
    assert service.appointment_summary()['pending_count'] == 201


def test_past_start_time_is_rejected_without_consuming_intake(workspace):
    body = values()
    body['start_at'] = datetime.now(timezone.utc) - timedelta(hours=2)
    body['end_at'] = datetime.now(timezone.utc) - timedelta(hours=1)
    with pytest.raises(ValueError, match='future'):
        service.submit_appointment(body, 'test-peer')
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 0
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_rate_limits')).scalar() == 0


def confirm(workspace, **changes):
    service.submit_appointment(values(**changes), 'test-peer')
    return service.review_appointment(request_id(workspace), {'action': 'confirmed', 'contacted': True}, 1)


def test_notifications_and_dashboard_count_follow_pending_review(workspace):
    body = values(appointment_type='field_visit')
    service.submit_appointment(body, 'test-peer')
    service.submit_appointment(body, 'test-peer')
    notifications = workspace.execute(text('SELECT user_id, target_path, read_at FROM staff_notifications')).all()
    assert len(notifications) == 1 and notifications[0].user_id == 1
    assert notifications[0].target_path == '/scheduling?requests=pending'
    assert service.appointment_summary()['pending_count'] == 1
    service.review_appointment(request_id(workspace), {'action': 'declined', 'decision_notes': 'No staff available.'}, 1)
    assert service.appointment_summary()['pending_count'] == 0
    assert workspace.execute(text('SELECT read_at FROM staff_notifications')).scalar() is not None


@pytest.mark.parametrize('appointment_type', ['field_visit', 'clean_up_drive'])
def test_nonplanting_confirmation_has_schedule_email_and_no_planter(workspace, appointment_type):
    reviewed = confirm(workspace, appointment_type=appointment_type)
    schedule = planting.get_planting_schedule(reviewed['schedule_id'])
    assert schedule['appointment_type'] == appointment_type
    assert workspace.execute(text('SELECT count(*) FROM planters')).scalar() == 0
    messages = []
    assert delivery.send_pending_appointment_emails(sender=lambda *args: messages.append(args))['sent'] == 1
    recipient, subject, body = messages[0]
    assert recipient == 'test@example.org'
    assert reviewed['reference'] in subject
    assert delivery.APPOINTMENT_TYPES[appointment_type] in body
    assert '08:00 AM' in body and '10:00 AM' in body and 'Philippine time' in body
    assert 'Username:' not in body and 'Password:' not in body and '/field' not in body
    with pytest.raises(ValueError, match='Only tree-planting'):
        planting.update_planting_schedule(reviewed['schedule_id'], project_site_id=12)


def test_tree_planting_credentials_are_encrypted_delivered_once_and_purged(workspace):
    reviewed = confirm(workspace)
    account = workspace.execute(text('SELECT username, password_hash FROM planters')).one()
    queued = workspace.execute(text('SELECT encrypted_message FROM like_appointment_emails')).scalar_one()
    assert account.username not in queued and 'Password:' not in queued
    assert workspace.execute(text('SELECT count(*) FROM organization_participants')).scalar() == 20
    messages = []
    assert delivery.send_pending_appointment_emails(sender=lambda *args: messages.append(args))['sent'] == 1
    body = messages[0][2]
    password = next(line.removeprefix('Password: ') for line in body.splitlines() if line.startswith('Password: '))
    assert PasswordHasher().verify(account.password_hash, password)
    assert f'Username: {account.username}' in body and 'https://example.org/field' in body
    assert password not in str(service.list_appointments())
    assert account.password_hash not in str(service.list_appointments())
    stored = workspace.execute(text('SELECT status, encrypted_message, sent_at FROM like_appointment_emails')).one()
    assert stored.status == 'sent' and stored.encrypted_message is None and stored.sent_at is not None
    assert delivery.send_pending_appointment_emails(sender=lambda *args: messages.append(args))['sent'] == 0
    service.review_appointment(reviewed['id'], {'action': 'confirmed', 'contacted': True}, 1)
    assert len(messages) == 1
    assert workspace.execute(text('SELECT count(*) FROM planters')).scalar() == 1


def test_delivery_failure_retries_same_credentials_without_leaking_provider_error(workspace):
    confirm(workspace)
    before = workspace.execute(text('SELECT username, password_hash FROM planters')).one()
    def unavailable(*args):
        raise RuntimeError('Sensitive provider text and credentials must never be stored')
    assert delivery.send_pending_appointment_emails(sender=unavailable) == {'configured': True, 'sent': 0, 'failed': 1}
    queued = workspace.execute(text('SELECT status, last_error, attempts, encrypted_message FROM like_appointment_emails')).one()
    assert queued.status == 'pending' and queued.last_error == 'RuntimeError' and queued.attempts == 1
    assert queued.encrypted_message
    messages = []
    assert delivery.send_pending_appointment_emails(sender=lambda *args: messages.append(args))['sent'] == 0
    workspace.exec_driver_sql("UPDATE like_appointment_emails SET next_attempt_at = CURRENT_TIMESTAMP - INTERVAL '1 minute'")
    assert delivery.send_pending_appointment_emails(sender=lambda *args: messages.append(args))['sent'] == 1
    assert before == workspace.execute(text('SELECT username, password_hash FROM planters')).one()


def test_existing_shared_account_and_device_slots_are_preserved(workspace):
    first = confirm(workspace)
    account = workspace.execute(text('SELECT id, username, password_hash, participant_count FROM planters')).one()
    workspace.execute(text("UPDATE organization_participants SET device_key_hash = 'claimed-device' WHERE slot = 1"))
    second = confirm(workspace, participants=30)
    assert first['schedule_id'] != second['schedule_id']
    assert account == workspace.execute(text('SELECT id, username, password_hash, participant_count FROM planters')).one()
    assert workspace.execute(text('SELECT device_key_hash FROM organization_participants WHERE slot = 1')).scalar() == 'claimed-device'
    messages = []
    delivery.send_pending_appointment_emails(request_id=second['id'], sender=lambda *args: messages.append(args))
    body = messages[0][2]
    assert f'Username: {account.username}' in body
    assert 'existing organization password' in body and 'Password:' not in body
    assert '20 participant devices' in body


def test_reserved_account_receives_login_without_losing_its_identity(workspace):
    first = confirm(workspace, appointment_type='field_visit')
    organization_id = planting.get_planting_schedule(first['schedule_id'])['organization_id']
    reserved_id = workspace.execute(text("INSERT INTO planters(organization_id, full_name) VALUES (:org, 'Example community') RETURNING id"), {'org': organization_id}).scalar_one()
    reviewed = confirm(workspace)
    assert workspace.execute(text('SELECT id FROM planters')).scalar_one() == reserved_id
    assert workspace.execute(text('SELECT username FROM planters')).scalar_one()
    assert workspace.execute(text('SELECT count(*) FROM organization_participants')).scalar() == 20
    assert reviewed['status'] == 'confirmed'


@pytest.mark.parametrize('setting', ['LIKE_EMAIL_ENCRYPTION_KEY', 'MANGROVISION_PUBLIC_URL'])
def test_missing_delivery_configuration_rolls_back_approval_and_account(workspace, monkeypatch, setting):
    monkeypatch.delenv(setting, raising=False)
    service.submit_appointment(values(), 'test-peer')
    with pytest.raises(ValueError, match='Configure'):
        service.review_appointment(request_id(workspace), {'action': 'confirmed', 'contacted': True}, 1)
    for table in ('organizations', 'planting_schedules', 'planters', 'organization_participants', 'like_appointment_emails'):
        assert workspace.execute(text(f'SELECT count(*) FROM {table}')).scalar() == 0
    assert service.appointment_summary()['pending_count'] == 1


def test_legacy_missing_email_can_be_corrected_before_confirmation(workspace):
    service.submit_appointment(values(appointment_type='field_visit'), 'test-peer')
    workspace.exec_driver_sql('UPDATE like_appointment_requests SET email = NULL')
    with pytest.raises(ValueError, match='valid email'):
        service.review_appointment(request_id(workspace), {'action': 'confirmed', 'contacted': True}, 1)
    reviewed = service.review_appointment(request_id(workspace), {'action': 'confirmed', 'contacted': True, 'email': 'corrected@example.org'}, 1)
    assert reviewed['email'] == 'corrected@example.org'
    assert workspace.execute(text('SELECT recipient_email FROM like_appointment_emails')).scalar_one() == 'corrected@example.org'


def test_cancelled_confirmed_schedule_does_not_send_queued_confirmation(workspace):
    confirm(workspace, appointment_type='field_visit')
    workspace.exec_driver_sql("UPDATE planting_schedules SET status = 'cancelled'")
    assert delivery.send_pending_appointment_emails(sender=lambda *args: pytest.fail('Cancelled appointment was emailed'))['sent'] == 0


def test_stale_delivery_claim_can_be_recovered(workspace):
    confirm(workspace, appointment_type='field_visit')
    workspace.exec_driver_sql("UPDATE like_appointment_emails SET status = 'sending', claimed_at = CURRENT_TIMESTAMP - INTERVAL '16 minutes'")
    messages = []
    assert delivery.send_pending_appointment_emails(sender=lambda *args: messages.append(args))['sent'] == 1
    assert len(messages) == 1
