"""Real PostgreSQL checks use only temporary tables and roll everything back."""

import importlib.util
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

import pytest
from sqlalchemy import text

import planting_database as planting
from mangrovision_db import like_appointments as service
from mangrovision_db.compat import CompatConnection, get_engine

pytestmark = pytest.mark.skipif(os.getenv('MANGROVISION_RUN_TEMP_LIKE_TESTS') != '1', reason='Temporary PostgreSQL checks are opt-in.')


@pytest.fixture()
def workspace(monkeypatch):
    try:
        connection = get_engine().connect()
    except Exception as issue:
        pytest.fail(f'Isolated database check could not connect ({type(issue).__name__}); connection details suppressed.', pytrace=False)
    transaction = connection.begin()
    try:
        connection.exec_driver_sql("""
            SET LOCAL statement_timeout = '20s';
            SET LOCAL search_path = pg_temp, public;
            CREATE TEMP TABLE users(id BIGINT PRIMARY KEY);
            INSERT INTO users VALUES (1);
            CREATE TEMP TABLE organizations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
                normalized_name TEXT UNIQUE NOT NULL, inspection_interval_days INTEGER NOT NULL,
                created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ
            );
            CREATE TEMP TABLE site_zones(id BIGINT PRIMARY KEY, name TEXT, polygon_geojson JSONB);
            CREATE TEMP TABLE planting_schedules (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_site_id BIGINT, organization TEXT NOT NULL, organization_id BIGINT,
                inspection_interval_days INTEGER, contact TEXT, title TEXT NOT NULL,
                start_at TIMESTAMPTZ NOT NULL, end_at TIMESTAMPTZ NOT NULL CHECK (end_at > start_at),
                expected_planters INTEGER, expected_seedlings INTEGER, status TEXT NOT NULL DEFAULT 'requested',
                notes TEXT, created_by_user_id BIGINT, updated_by_user_id BIGINT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ
            );
        """)
        spec = importlib.util.spec_from_file_location('like_migration', Path(__file__).resolve().parents[1] / 'alembic/versions/20261006_0013_like_appointments.py')
        migration = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(migration)
        statements = []
        monkeypatch.setattr(migration.op, 'execute', statements.append)
        migration.upgrade()
        for statement in statements:
            # Only session-local objects are created or changed. Never run the migration against live tables.
            statement = statement.replace('mangrovision.', 'pg_temp.').replace('CREATE TABLE pg_temp.', 'CREATE TEMP TABLE pg_temp.')
            connection.exec_driver_sql(statement)

        class TempConnection(CompatConnection):
            def __init__(self):
                super().__init__(connection)
                self.savepoint = connection.begin_nested()
            def commit(self):
                self.savepoint.commit()
            def rollback(self):
                if self.savepoint.is_active:
                    self.savepoint.rollback()
            def close(self):
                self.rollback()

        monkeypatch.setattr(planting, '_get_connection', TempConnection)
        yield connection
    finally:
        transaction.rollback()
        connection.close()


def values(**changes):
    start = (datetime.now(timezone.utc) + timedelta(days=3)).replace(hour=0, minute=0, second=0, microsecond=0)
    return dict(submission_key=uuid4(), organization='Example community', contact_name='Test coordinator',
                phone='09123456789', email='test@example.org', title='Community planting',
                start_at=start, end_at=start + timedelta(hours=2), participants=20,
                notes='For test only', consent=True, website='', **changes)


def request_id(connection):
    return connection.execute(text('SELECT id FROM like_appointment_requests ORDER BY id DESC LIMIT 1')).scalar_one()


def test_request_is_private_and_does_not_register_an_organization(workspace):
    result = service.submit_appointment(values(), 'test-peer')
    assert set(result) == {'reference', 'status', 'timezone'}
    assert result['reference'].startswith('LIKE-')
    assert workspace.execute(text('SELECT count(*) FROM organizations')).scalar() == 0
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 0
    private = service.list_appointments()[0]
    assert private['phone'] == '09123456789'
    assert 'submission_key' not in private and 'payload_hash' not in private


def test_submit_retries_once_and_rejects_changed_payload(workspace):
    body = values()
    first = service.submit_appointment(body, 'test-peer')
    assert service.submit_appointment(body, 'test-peer') == first
    with pytest.raises(service.AppointmentConflict):
        service.submit_appointment({**body, 'participants': 21}, 'test-peer')
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 1


def test_confirmation_is_atomic_and_idempotent(workspace):
    body = values()
    service.submit_appointment(body, 'test-peer')
    review = {'action': 'confirmed', 'contacted': True, 'start_at': body['start_at'] + timedelta(hours=1), 'end_at': body['end_at'] + timedelta(hours=1)}
    first = service.review_appointment(request_id(workspace), review, 1)
    assert service.review_appointment(first['id'], review, 1)['schedule_id'] == first['schedule_id']
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 1
    schedule = planting.get_planting_schedule(first['schedule_id'])
    assert schedule['source'] == 'website' and schedule['status'] == 'confirmed'
    assert schedule['start_time'] == '09:00' and schedule['inspection_interval_days'] == 14
    assert workspace.execute(text('SELECT count(*) FROM organizations')).scalar() == 1
    assert workspace.execute(text('SELECT contacted FROM like_appointment_requests')).scalar() is True


def test_confirmation_requires_contact_and_failed_approval_leaves_no_schedule(workspace, monkeypatch):
    service.submit_appointment(values(), 'test-peer')
    with pytest.raises(ValueError, match='Contact the requester'):
        service.review_appointment(request_id(workspace), {'action': 'confirmed'}, 1)
    original = planting.create_planting_schedule
    def fail_after_insert(**kwargs):
        original(**kwargs)
        raise RuntimeError('Simulated failure after schedule insertion')
    monkeypatch.setattr(planting, 'create_planting_schedule', fail_after_insert)
    with pytest.raises(RuntimeError):
        service.review_appointment(request_id(workspace), {'action': 'confirmed', 'contacted': True}, 1)
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 0
    assert workspace.execute(text('SELECT count(*) FROM organizations')).scalar() == 0
    assert workspace.execute(text('SELECT status FROM like_appointment_requests')).scalar() == 'pending'


@pytest.mark.parametrize('action', ['declined', 'cancelled'])
def test_decline_and_cancel_require_reason_and_create_no_schedule(workspace, action):
    service.submit_appointment(values(), 'test-peer')
    with pytest.raises(ValueError, match='reason'):
        service.review_appointment(request_id(workspace), {'action': action}, 1)
    reviewed = service.review_appointment(request_id(workspace), {'action': action, 'decision_notes': 'Agreed another activity instead.'}, 1)
    assert reviewed['status'] == action
    assert workspace.execute(text('SELECT count(*) FROM planting_schedules')).scalar() == 0


def test_rate_limit_preserves_successful_requests_and_retry_receipt(workspace):
    first = values()
    receipt = service.submit_appointment(first, 'test-peer')
    for _ in range(4):
        service.submit_appointment(values(), 'test-peer')
    with pytest.raises(service.AppointmentRateLimit):
        service.submit_appointment(values(), 'test-peer')
    assert service.submit_appointment(first, 'test-peer') == receipt
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 5


def test_manual_schedule_creation_still_works(workspace):
    body = values()
    schedule = planting.create_planting_schedule(organization=body['organization'], inspection_interval_days=14,
        title='Staff-assisted planting', start_at=body['start_at'], end_at=body['end_at'], created_by_user_id=1)
    assert schedule['source'] == 'staff' and schedule['status'] == 'requested'
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 0


def test_client_database_roles_cannot_access_request_tables(workspace):
    roles = workspace.execute(text("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")).scalars().all()
    for role in roles:
        for table in ('like_appointment_requests', 'like_appointment_rate_limits'):
            for privilege in ('SELECT', 'INSERT', 'UPDATE', 'DELETE'):
                assert workspace.execute(text('SELECT has_table_privilege(:role, :table, :privilege)'),
                    {'role': role, 'table': f'pg_temp.{table}', 'privilege': privilege}).scalar() is False


def test_all_pending_requests_remain_visible_beyond_history_limit(workspace):
    workspace.exec_driver_sql("""
        INSERT INTO like_appointment_requests
            (reference, submission_key, payload_hash, organization, contact_name, phone,
             title, start_at, end_at, participants, status)
        SELECT 'LIKE-QUEUE-' || n, md5('queue-' || n)::uuid, 'test-hash', 'Test group',
            'Test coordinator', '09123456789', 'Test planting', CURRENT_TIMESTAMP + INTERVAL '1 day',
            CURRENT_TIMESTAMP + INTERVAL '1 day 2 hours', 20, 'pending'
        FROM generate_series(1, 201) n;
    """)
    assert len(service.list_appointments()) == 201


def test_past_start_time_is_rejected_without_consuming_intake(workspace):
    body = values()
    body['start_at'] = datetime.now(timezone.utc) - timedelta(hours=2)
    body['end_at'] = datetime.now(timezone.utc) - timedelta(hours=1)
    with pytest.raises(ValueError, match='future'):
        service.submit_appointment(body, 'test-peer')
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_requests')).scalar() == 0
    assert workspace.execute(text('SELECT count(*) FROM like_appointment_rate_limits')).scalar() == 0
