"""Create the PostgreSQL/PostGIS production baseline."""

from alembic import op

revision = "20260831_0001"
down_revision = None
branch_labels = None
depends_on = None


DDL = r"""
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;
DO $role$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mangrovision') THEN
        CREATE ROLE mangrovision
            NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
    END IF;
END
$role$;
CREATE SCHEMA IF NOT EXISTS mangrovision AUTHORIZATION CURRENT_USER;
REVOKE ALL ON SCHEMA mangrovision FROM PUBLIC;
SET search_path TO mangrovision, extensions, public;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'planner',
    organization TEXT,
    password_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_users_full_name_ci ON users (lower(full_name));

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL UNIQUE,
    inspection_interval_days INTEGER NOT NULL CHECK (inspection_interval_days BETWEEN 1 AND 3650),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_organizations_name_ci ON organizations (lower(name));

CREATE TABLE project_sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    notes TEXT,
    polygon_geojson JSONB NOT NULL,
    geometry extensions.geometry(MultiPolygon, 4326) GENERATED ALWAYS AS (
        extensions.ST_Multi(extensions.ST_SetSRID(extensions.ST_GeomFromGeoJSON(polygon_geojson::text), 4326))
    ) STORED,
    organization_id BIGINT REFERENCES organizations(id) ON DELETE RESTRICT,
    inspection_interval_days INTEGER CHECK (inspection_interval_days IS NULL OR inspection_interval_days BETWEEN 1 AND 3650),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    CONSTRAINT ck_project_sites_valid_geometry CHECK (extensions.ST_IsValid(geometry))
);
CREATE INDEX idx_project_sites_geometry ON project_sites USING GIST (geometry);
CREATE INDEX idx_project_sites_organization ON project_sites (organization_id);
CREATE VIEW site_zones WITH (security_invoker = true) AS
SELECT id, name, notes, polygon_geojson, created_at, updated_at,
       organization_id, inspection_interval_days
FROM project_sites;

CREATE TABLE analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    image_name TEXT NOT NULL,
    analyzed_at TIMESTAMPTZ NOT NULL,
    center_lat DOUBLE PRECISION,
    center_lon DOUBLE PRECISION,
    center_location extensions.geometry(Point, 4326) GENERATED ALWAYS AS (
        CASE WHEN center_lat IS NULL OR center_lon IS NULL THEN NULL
             ELSE extensions.ST_SetSRID(extensions.ST_MakePoint(center_lon, center_lat), 4326) END
    ) STORED,
    altitude_m DOUBLE PRECISION,
    gsd_cm DOUBLE PRECISION,
    coverage_w_m DOUBLE PRECISION,
    coverage_h_m DOUBLE PRECISION,
    total_area_m2 DOUBLE PRECISION,
    canopy_count INTEGER,
    canopy_area_m2 DOUBLE PRECISION,
    canopy_coverage_pct DOUBLE PRECISION,
    polygon_count INTEGER NOT NULL DEFAULT 0,
    danger_area_m2 DOUBLE PRECISION,
    danger_pct DOUBLE PRECISION,
    plantable_area_m2 DOUBLE PRECISION,
    plantable_pct DOUBLE PRECISION,
    hexagon_count INTEGER,
    ai_confidence DOUBLE PRECISION,
    canopy_buffer_m DOUBLE PRECISION,
    hexagon_size_m DOUBLE PRECISION,
    forbidden_filtered INTEGER NOT NULL DEFAULT 0,
    eroded_filtered INTEGER NOT NULL DEFAULT 0,
    canopy_polygons_geojson JSONB,
    analysis_detail_json JSONB,
    species TEXT,
    planting_distance_m DOUBLE PRECISION,
    project_site_id BIGINT REFERENCES project_sites(id) ON DELETE SET NULL,
    footprint_geojson JSONB,
    footprint extensions.geometry(MultiPolygon, 4326) GENERATED ALWAYS AS (
        CASE WHEN footprint_geojson IS NULL THEN NULL
             ELSE extensions.ST_Multi(extensions.ST_SetSRID(extensions.ST_GeomFromGeoJSON(footprint_geojson::text), 4326)) END
    ) STORED,
    footprint_quality TEXT,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_analyses_valid_footprint CHECK (
        footprint IS NULL OR extensions.ST_IsValid(footprint)
    )
);
CREATE INDEX idx_analyses_user ON analyses (user_id);
CREATE INDEX idx_analyses_project_site ON analyses (project_site_id);
CREATE INDEX idx_analyses_date ON analyses (analyzed_at DESC);
CREATE INDEX idx_analyses_center_geometry ON analyses USING GIST (center_location);
CREATE INDEX idx_analyses_footprint ON analyses USING GIST (footprint);

CREATE TABLE planting_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT NOT NULL REFERENCES analyses(id) ON DELETE CASCADE,
    point_num INTEGER NOT NULL,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    location extensions.geometry(Point, 4326) GENERATED ALWAYS AS (
        extensions.ST_SetSRID(extensions.ST_MakePoint(longitude, latitude), 4326)
    ) STORED,
    pixel_x INTEGER,
    pixel_y INTEGER,
    buffer_m DOUBLE PRECISION,
    area_m2 DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'planted', 'skipped')),
    planted_at TIMESTAMPTZ,
    planted_date DATE,
    deleted_at TIMESTAMPTZ,
    deletion_reason TEXT,
    deletion_batch_id TEXT,
    deletion_color TEXT,
    death_at TIMESTAMPTZ,
    death_reason TEXT,
    death_reason_category TEXT,
    death_notes TEXT,
    UNIQUE (analysis_id, point_num)
);
CREATE INDEX idx_points_analysis ON planting_points (analysis_id);
CREATE INDEX idx_points_status ON planting_points (status) WHERE deleted_at IS NULL;
CREATE INDEX idx_points_location ON planting_points USING GIST (location);

CREATE TABLE planters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    organization_id BIGINT REFERENCES organizations(id) ON DELETE RESTRICT,
    phone TEXT,
    base_label TEXT,
    base_lat DOUBLE PRECISION,
    base_lon DOUBLE PRECISION,
    base_location extensions.geometry(Point, 4326) GENERATED ALWAYS AS (
        CASE WHEN base_lat IS NULL OR base_lon IS NULL THEN NULL
             ELSE extensions.ST_SetSRID(extensions.ST_MakePoint(base_lon, base_lat), 4326) END
    ) STORED,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    notes TEXT,
    username TEXT,
    password_hash TEXT,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uq_planters_username_ci ON planters (lower(username)) WHERE username IS NOT NULL;
CREATE INDEX idx_planters_organization ON planters (organization_id);
CREATE INDEX idx_planters_status ON planters (status);

CREATE TABLE planter_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planter_id BIGINT NOT NULL REFERENCES planters(id) ON DELETE CASCADE,
    assigned_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    assignment_date DATE NOT NULL,
    travel_mode TEXT NOT NULL DEFAULT 'walking',
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'archived')),
    species TEXT,
    notes TEXT,
    project_site_id BIGINT REFERENCES project_sites(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_planter_assignments_planter ON planter_assignments (planter_id);
CREATE INDEX idx_planter_assignments_assigned_by ON planter_assignments (assigned_by_user_id);
CREATE INDEX idx_planter_assignments_project_site ON planter_assignments (project_site_id);
CREATE INDEX idx_planter_assignments_status ON planter_assignments (status);

CREATE TABLE planter_assignment_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL REFERENCES planter_assignments(id) ON DELETE CASCADE,
    planting_point_id BIGINT NOT NULL REFERENCES planting_points(id) ON DELETE CASCADE,
    sequence_num INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'skipped')),
    completed_at TIMESTAMPTZ,
    notes TEXT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    skip_reason TEXT,
    UNIQUE (assignment_id, planting_point_id),
    UNIQUE (assignment_id, sequence_num)
);
CREATE INDEX idx_assignment_points_point ON planter_assignment_points (planting_point_id);
CREATE INDEX idx_assignment_points_status ON planter_assignment_points (status);

CREATE TABLE auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type TEXT NOT NULL CHECK (subject_type IN ('user', 'planter')),
    subject_id BIGINT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_auth_sessions_active
    ON auth_sessions (subject_type, token_hash, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX idx_auth_sessions_subject ON auth_sessions (subject_type, subject_id);

CREATE TABLE map_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_type TEXT NOT NULL DEFAULT 'warning'
        CHECK (zone_type IN ('gis_coverage', 'eroded', 'forbidden', 'warning')),
    name TEXT NOT NULL,
    warning_type TEXT DEFAULT 'planner_warning',
    severity TEXT DEFAULT 'medium' CHECK (severity IS NULL OR severity IN ('low', 'medium', 'high')),
    notes TEXT,
    properties JSONB NOT NULL DEFAULT '{}'::jsonb,
    polygon_geojson JSONB NOT NULL,
    geometry extensions.geometry(MultiPolygon, 4326) GENERATED ALWAYS AS (
        extensions.ST_Multi(extensions.ST_SetSRID(extensions.ST_GeomFromGeoJSON(polygon_geojson::text), 4326))
    ) STORED,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_map_zones_valid_geometry CHECK (extensions.ST_IsValid(geometry))
);
CREATE INDEX idx_map_zones_geometry ON map_zones USING GIST (geometry);
CREATE INDEX idx_map_zones_active_type ON map_zones (zone_type) WHERE deleted_at IS NULL;
CREATE INDEX idx_map_zones_created_by ON map_zones (created_by_user_id);
CREATE UNIQUE INDEX uq_map_zones_migration_source
    ON map_zones (
        (properties->>'migration_source_sha256'),
        (properties->>'migration_feature_index')
    )
    WHERE properties ? 'migration_source_sha256'
      AND properties ? 'migration_feature_index';
CREATE VIEW warning_zones WITH (security_invoker = true) AS
SELECT id, name, warning_type, severity, notes, polygon_geojson,
       created_at, updated_at
FROM map_zones
WHERE zone_type = 'warning' AND deleted_at IS NULL;

CREATE TABLE planting_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL UNIQUE,
    planting_point_id BIGINT REFERENCES planting_points(id) ON DELETE SET NULL,
    assignment_point_id BIGINT REFERENCES planter_assignment_points(id) ON DELETE SET NULL,
    assignment_id BIGINT REFERENCES planter_assignments(id) ON DELETE SET NULL,
    project_site_id BIGINT REFERENCES project_sites(id) ON DELETE SET NULL,
    planter_id BIGINT REFERENCES planters(id) ON DELETE SET NULL,
    species TEXT,
    planted_at TIMESTAMPTZ NOT NULL,
    point_num INTEGER,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location extensions.geometry(Point, 4326) GENERATED ALWAYS AS (
        CASE WHEN latitude IS NULL OR longitude IS NULL THEN NULL
             ELSE extensions.ST_SetSRID(extensions.ST_MakePoint(longitude, latitude), 4326) END
    ) STORED,
    source TEXT NOT NULL DEFAULT 'field_completion',
    site_attribution_source TEXT NOT NULL DEFAULT 'planting_snapshot',
    inspection_interval_days INTEGER CHECK (inspection_interval_days IS NULL OR inspection_interval_days BETWEEN 1 AND 3650),
    closed_at TIMESTAMPTZ,
    closure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_planting_events_point ON planting_events (planting_point_id, planted_at);
CREATE INDEX idx_planting_events_assignment_point ON planting_events (assignment_point_id);
CREATE INDEX idx_planting_events_assignment ON planting_events (assignment_id, planted_at);
CREATE INDEX idx_planting_events_site ON planting_events (project_site_id, planted_at);
CREATE INDEX idx_planting_events_planter ON planting_events (planter_id);
CREATE INDEX idx_planting_events_location ON planting_events USING GIST (location);

CREATE TABLE point_death_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planting_point_id BIGINT NOT NULL REFERENCES planting_points(id) ON DELETE CASCADE,
    assignment_id BIGINT REFERENCES planter_assignments(id) ON DELETE SET NULL,
    planting_event_id BIGINT REFERENCES planting_events(id) ON DELETE SET NULL,
    monitoring_observation_id BIGINT,
    death_at TIMESTAMPTZ NOT NULL,
    reason_category TEXT NOT NULL,
    reason_label TEXT,
    notes TEXT,
    planter_id BIGINT REFERENCES planters(id) ON DELETE SET NULL,
    planter_name TEXT,
    species TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_death_records_point ON point_death_records (planting_point_id);
CREATE INDEX idx_death_records_assignment ON point_death_records (assignment_id);
CREATE INDEX idx_death_records_planting_event ON point_death_records (planting_event_id);
CREATE INDEX idx_death_records_monitoring ON point_death_records (monitoring_observation_id);
CREATE INDEX idx_death_records_planter ON point_death_records (planter_id);
CREATE INDEX idx_death_records_death_at ON point_death_records (death_at);

CREATE TABLE monitoring_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planting_event_id BIGINT NOT NULL REFERENCES planting_events(id) ON DELETE CASCADE,
    interval_days INTEGER NOT NULL CHECK (interval_days > 0),
    inspected_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('alive', 'dead', 'missing')),
    condition TEXT,
    height_cm DOUBLE PRECISION CHECK (height_cm IS NULL OR height_cm >= 0),
    photo_path TEXT,
    notes TEXT,
    actions_taken TEXT,
    death_reason_category TEXT,
    inspector_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    death_record_id BIGINT REFERENCES point_death_records(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    UNIQUE (planting_event_id, interval_days)
);
ALTER TABLE point_death_records
    ADD CONSTRAINT fk_death_monitoring_observation
    FOREIGN KEY (monitoring_observation_id) REFERENCES monitoring_observations(id) ON DELETE SET NULL;
CREATE INDEX idx_monitoring_observations_date ON monitoring_observations (inspected_at);
CREATE INDEX idx_monitoring_observations_inspector ON monitoring_observations (inspector_user_id);
CREATE INDEX idx_monitoring_observations_death_record ON monitoring_observations (death_record_id);

CREATE TABLE organization_monitoring_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    monitored_at TIMESTAMPTZ NOT NULL,
    alive_count INTEGER NOT NULL CHECK (alive_count >= 0),
    dead_count INTEGER NOT NULL CHECK (dead_count >= 0),
    average_height_cm DOUBLE PRECISION NOT NULL CHECK (average_height_cm >= 0),
    health_status TEXT NOT NULL CHECK (health_status IN ('excellent', 'good', 'fair', 'poor', 'critical')),
    actions_taken TEXT NOT NULL,
    inspector_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_organization_monitoring_date ON organization_monitoring_records (monitored_at DESC);
CREATE INDEX idx_organization_monitoring_organization ON organization_monitoring_records (organization_id);
CREATE INDEX idx_organization_monitoring_inspector ON organization_monitoring_records (inspector_user_id);

CREATE TABLE planting_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_site_id BIGINT REFERENCES project_sites(id) ON DELETE RESTRICT,
    organization TEXT NOT NULL,
    organization_id BIGINT REFERENCES organizations(id) ON DELETE RESTRICT,
    inspection_interval_days INTEGER CHECK (inspection_interval_days IS NULL OR inspection_interval_days BETWEEN 1 AND 3650),
    contact TEXT,
    title TEXT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL CHECK (end_at > start_at),
    expected_planters INTEGER CHECK (expected_planters IS NULL OR expected_planters >= 0),
    expected_seedlings INTEGER CHECK (expected_seedlings IS NULL OR expected_seedlings >= 0),
    status TEXT NOT NULL DEFAULT 'requested',
    notes TEXT,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_planting_schedules_site_time ON planting_schedules (project_site_id, start_at);
CREATE INDEX idx_planting_schedules_organization ON planting_schedules (organization_id);
CREATE INDEX idx_planting_schedules_created_by ON planting_schedules (created_by_user_id);
CREATE INDEX idx_planting_schedules_updated_by ON planting_schedules (updated_by_user_id);
CREATE INDEX idx_planting_schedules_status_time ON planting_schedules (status, start_at);

CREATE TABLE dashboard_settings (
    year INTEGER PRIMARY KEY,
    annual_planting_target INTEGER CHECK (annual_planting_target IS NULL OR annual_planting_target >= 0),
    min_survival_target_pct DOUBLE PRECISION CHECK (
        min_survival_target_pct IS NULL OR min_survival_target_pct BETWEEN 0 AND 100
    ),
    inspection_intervals_json JSONB NOT NULL DEFAULT '[30, 90, 180, 365]'::jsonb,
    inspection_weekdays_json JSONB NOT NULL DEFAULT '[2, 5]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_dashboard_settings_updated_by ON dashboard_settings (updated_by_user_id);

CREATE TABLE analysis_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT NOT NULL REFERENCES analyses(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('original', 'visualization')),
    object_key TEXT NOT NULL UNIQUE,
    content_type TEXT NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
    byte_size BIGINT NOT NULL CHECK (byte_size > 0),
    sha256 CHAR(64) NOT NULL,
    lifecycle_state TEXT NOT NULL DEFAULT 'ready'
        CHECK (lifecycle_state IN ('pending', 'ready', 'delete_pending', 'failed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (analysis_id, kind)
);
CREATE TABLE object_cleanup_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key TEXT NOT NULL UNIQUE,
    reason TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ
);

CREATE TABLE migration_imports (
    id UUID PRIMARY KEY,
    source_sha256 CHAR(64) NOT NULL UNIQUE,
    source_path TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('running', 'failed', 'complete')),
    manifest JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_error TEXT
);

CREATE OR REPLACE FUNCTION set_assignment_point_timestamps()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = mangrovision, extensions, pg_catalog
AS $fn$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.assigned_at := COALESCE(NEW.assigned_at, CURRENT_TIMESTAMP);
        NEW.status_changed_at := COALESCE(NEW.status_changed_at, CURRENT_TIMESTAMP);
    ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
        NEW.status_changed_at := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END
$fn$;

CREATE TRIGGER trg_assignment_point_timestamps
BEFORE INSERT OR UPDATE OF status ON planter_assignment_points
FOR EACH ROW EXECUTE FUNCTION set_assignment_point_timestamps();

CREATE OR REPLACE FUNCTION maintain_planting_event()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = mangrovision, extensions, pg_catalog
AS $fn$
BEGIN
    IF OLD.status = 'completed' AND NEW.status <> 'completed' THEN
        UPDATE planting_events
           SET closed_at = COALESCE(closed_at, CURRENT_TIMESTAMP),
               closure_reason = 'completion_reversed'
         WHERE id = (
             SELECT id FROM planting_events
              WHERE assignment_point_id = NEW.id AND closed_at IS NULL
              ORDER BY planted_at DESC, id DESC LIMIT 1
         );
    END IF;

    IF NEW.status = 'completed' AND OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO planting_events (
            source_key, planting_point_id, assignment_point_id, assignment_id,
            project_site_id, planter_id, species, planted_at, point_num,
            latitude, longitude, source, inspection_interval_days
        )
        SELECT
            'assignment-point:' || NEW.id || ':' ||
                COALESCE(NEW.completed_at, CURRENT_TIMESTAMP)::text || ':' ||
                substr(md5(random()::text), 1, 8),
            pp.id, NEW.id, pa.id,
            COALESCE(pa.project_site_id, a.project_site_id),
            pa.planter_id,
            COALESCE(NULLIF(trim(pa.species), ''), NULLIF(trim(a.species), '')),
            COALESCE(NEW.completed_at, CURRENT_TIMESTAMP),
            pp.point_num, pp.latitude, pp.longitude, 'field_completion',
            COALESCE(ps.inspection_interval_days, 30)
        FROM planter_assignments pa
        JOIN planting_points pp ON pp.id = NEW.planting_point_id
        JOIN analyses a ON a.id = pp.analysis_id
        LEFT JOIN project_sites ps ON ps.id = COALESCE(pa.project_site_id, a.project_site_id)
        WHERE pa.id = NEW.assignment_id
        ON CONFLICT (source_key) DO NOTHING;
    END IF;
    RETURN NEW;
END
$fn$;

CREATE TRIGGER trg_assignment_point_planting_event
AFTER UPDATE OF status ON planter_assignment_points
FOR EACH ROW EXECUTE FUNCTION maintain_planting_event();

REVOKE ALL ON FUNCTION set_assignment_point_timestamps() FROM PUBLIC;
REVOKE ALL ON FUNCTION maintain_planting_event() FROM PUBLIC;

DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mangrovision') THEN
        GRANT USAGE ON SCHEMA mangrovision, extensions TO mangrovision;
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mangrovision TO mangrovision;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA mangrovision TO mangrovision;
        ALTER DEFAULT PRIVILEGES IN SCHEMA mangrovision
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mangrovision;
        ALTER DEFAULT PRIVILEGES IN SCHEMA mangrovision
            GRANT USAGE, SELECT ON SEQUENCES TO mangrovision;
    END IF;
END
$grant$;
"""


def upgrade() -> None:
    op.get_bind().exec_driver_sql(DDL)


def downgrade() -> None:
    # Alembic stores its own version table in this schema. Keep that table and
    # the schema alive so Alembic can remove the revision row after this
    # function returns.
    op.execute(r"""
        DO $cleanup$
        DECLARE item record;
        BEGIN
            FOR item IN
                SELECT tablename
                FROM pg_tables
                WHERE schemaname = 'mangrovision'
                  AND tablename <> 'alembic_version'
            LOOP
                EXECUTE format('DROP TABLE mangrovision.%I CASCADE', item.tablename);
            END LOOP;
            FOR item IN
                SELECT p.proname, pg_get_function_identity_arguments(p.oid) AS arguments
                FROM pg_proc p
                JOIN pg_namespace n ON n.oid = p.pronamespace
                WHERE n.nspname = 'mangrovision'
            LOOP
                EXECUTE format(
                    'DROP FUNCTION mangrovision.%I(%s) CASCADE',
                    item.proname,
                    item.arguments
                );
            END LOOP;
        END
        $cleanup$;
    """)
