"""Record LGU planting, seedling details, activity, and reminder delivery."""

from alembic import op

revision = "20260928_0009"
down_revision = "20260916_0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute("SET LOCAL statement_timeout = '60s'")
    op.execute("""
        UPDATE mangrovision.organizations SET inspection_interval_days = 14
            WHERE inspection_interval_days <> 14;
        UPDATE mangrovision.project_sites SET inspection_interval_days = 14
            WHERE inspection_interval_days IS NOT NULL AND inspection_interval_days <> 14;
        UPDATE mangrovision.planting_schedules SET inspection_interval_days = 14
            WHERE inspection_interval_days IS NOT NULL AND inspection_interval_days <> 14;
        UPDATE mangrovision.planting_events SET inspection_interval_days = 14
            WHERE inspection_interval_days IS DISTINCT FROM 14;
        ALTER TABLE mangrovision.planting_events
            ADD COLUMN planted_by_user_id BIGINT REFERENCES mangrovision.users(id) ON DELETE RESTRICT,
            ADD COLUMN initial_height_cm DOUBLE PRECISION CHECK (
                initial_height_cm IS NULL OR (initial_height_cm >= 0 AND initial_height_cm <= 1000)
            ),
            ADD COLUMN initial_condition TEXT CHECK (
                initial_condition IS NULL OR initial_condition IN ('healthy', 'fair', 'stressed', 'unknown')
            ),
            ADD COLUMN initial_notes TEXT CHECK (initial_notes IS NULL OR length(initial_notes) <= 1000);
        ALTER TABLE mangrovision.planting_events
            ADD CONSTRAINT ck_lgu_direct_actor
            CHECK (source <> 'lgu_direct' OR (planted_by_user_id IS NOT NULL AND planter_id IS NULL));
        CREATE INDEX idx_planting_events_lgu_actor
            ON mangrovision.planting_events (planted_by_user_id, planted_at DESC)
            WHERE planted_by_user_id IS NOT NULL;

        CREATE OR REPLACE FUNCTION mangrovision.maintain_planting_event()
        RETURNS trigger LANGUAGE plpgsql
        SET search_path = mangrovision, extensions, pg_catalog
        AS $fn$
        BEGIN
            IF OLD.status = 'completed' AND NEW.status <> 'completed' THEN
                UPDATE planting_events
                   SET closed_at = COALESCE(closed_at, CURRENT_TIMESTAMP),
                       closure_reason = 'completion_reversed'
                 WHERE id = (
                     SELECT id FROM planting_events
                     WHERE assignment_point_id = NEW.id AND closed_at IS NULL
                     ORDER BY planted_at DESC, id DESC LIMIT 1
                 );
            END IF;

            IF NEW.status = 'completed' AND OLD.status IS DISTINCT FROM NEW.status THEN
                INSERT INTO planting_events (
                    source_key, planting_point_id, assignment_point_id, assignment_id,
                    project_site_id, planter_id, species, planted_at, point_num,
                    latitude, longitude, source, inspection_interval_days
                )
                SELECT
                    'assignment-point:' || NEW.id || ':' ||
                        COALESCE(NEW.completed_at, CURRENT_TIMESTAMP)::text || ':' ||
                        substr(md5(random()::text), 1, 8),
                    pp.id, NEW.id, pa.id,
                    COALESCE(pa.project_site_id, a.project_site_id),
                    pa.planter_id,
                    COALESCE(NULLIF(trim(pa.species), ''), NULLIF(trim(a.species), '')),
                    COALESCE(NEW.completed_at, CURRENT_TIMESTAMP),
                    pp.point_num, pp.latitude, pp.longitude, 'field_completion', 14
                FROM planter_assignments pa
                JOIN planting_points pp ON pp.id = NEW.planting_point_id
                JOIN analyses a ON a.id = pp.analysis_id
                WHERE pa.id = NEW.assignment_id
                ON CONFLICT (source_key) DO NOTHING;
            END IF;
            RETURN NEW;
        END
        $fn$;

        CREATE TABLE mangrovision.activity_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action TEXT NOT NULL,
            actor_type TEXT NOT NULL CHECK (actor_type IN ('staff', 'planter', 'system')),
            actor_user_id BIGINT REFERENCES mangrovision.users(id) ON DELETE SET NULL,
            actor_planter_id BIGINT REFERENCES mangrovision.planters(id) ON DELETE SET NULL,
            participant_slot INTEGER,
            organization_id BIGINT REFERENCES mangrovision.organizations(id) ON DELETE SET NULL,
            project_site_id BIGINT REFERENCES mangrovision.project_sites(id) ON DELETE SET NULL,
            planting_point_id BIGINT REFERENCES mangrovision.planting_points(id) ON DELETE SET NULL,
            planting_event_id BIGINT REFERENCES mangrovision.planting_events(id) ON DELETE SET NULL,
            summary TEXT NOT NULL,
            details JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX idx_activity_logs_recent ON mangrovision.activity_logs (created_at DESC, id DESC);
        CREATE INDEX idx_activity_logs_organization
            ON mangrovision.activity_logs (organization_id, created_at DESC, id DESC)
            WHERE organization_id IS NOT NULL;

        CREATE TABLE mangrovision.staff_notifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES mangrovision.users(id) ON DELETE CASCADE,
            event_key TEXT NOT NULL,
            kind TEXT NOT NULL,
            title TEXT NOT NULL,
            body TEXT NOT NULL,
            target_path TEXT NOT NULL,
            due_date DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            read_at TIMESTAMPTZ,
            UNIQUE (user_id, event_key)
        );
        CREATE INDEX idx_staff_notifications_unread
            ON mangrovision.staff_notifications (user_id, created_at DESC, id DESC)
            WHERE read_at IS NULL;

        CREATE TABLE mangrovision.email_reminders (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_key TEXT NOT NULL,
            recipient_email TEXT NOT NULL,
            subject TEXT NOT NULL,
            body TEXT NOT NULL,
            send_on DATE NOT NULL,
            monitoring_due_date DATE NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent')),
            attempts INTEGER NOT NULL DEFAULT 0,
            claimed_at TIMESTAMPTZ,
            sent_at TIMESTAMPTZ,
            last_error TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (recipient_email, event_key)
        );
        CREATE INDEX idx_email_reminders_pending
            ON mangrovision.email_reminders (send_on, id)
            WHERE status <> 'sent';

        REVOKE ALL ON mangrovision.activity_logs, mangrovision.staff_notifications,
            mangrovision.email_reminders FROM PUBLIC;
        ALTER TABLE mangrovision.activity_logs ENABLE ROW LEVEL SECURITY;
        ALTER TABLE mangrovision.staff_notifications ENABLE ROW LEVEL SECURITY;
        ALTER TABLE mangrovision.email_reminders ENABLE ROW LEVEL SECURITY;
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mangrovision') THEN
                GRANT SELECT, INSERT ON mangrovision.activity_logs TO mangrovision;
                GRANT SELECT, INSERT, UPDATE ON mangrovision.staff_notifications,
                    mangrovision.email_reminders TO mangrovision;
                GRANT USAGE, SELECT ON SEQUENCE mangrovision.activity_logs_id_seq,
                    mangrovision.staff_notifications_id_seq,
                    mangrovision.email_reminders_id_seq TO mangrovision;
                CREATE POLICY activity_backend ON mangrovision.activity_logs
                    FOR ALL TO mangrovision USING (true) WITH CHECK (true);
                CREATE POLICY notifications_backend ON mangrovision.staff_notifications
                    FOR ALL TO mangrovision USING (true) WITH CHECK (true);
                CREATE POLICY email_backend ON mangrovision.email_reminders
                    FOR ALL TO mangrovision USING (true) WITH CHECK (true);
            END IF;
        END $$;
    """)


def downgrade() -> None:
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM mangrovision.activity_logs)
                OR EXISTS (SELECT 1 FROM mangrovision.staff_notifications)
                OR EXISTS (SELECT 1 FROM mangrovision.email_reminders)
                OR EXISTS (SELECT 1 FROM mangrovision.planting_events WHERE planted_by_user_id IS NOT NULL)
                OR EXISTS (SELECT 1 FROM mangrovision.planting_events WHERE initial_height_cm IS NOT NULL
                    OR initial_condition IS NOT NULL OR initial_notes IS NOT NULL) THEN
                RAISE EXCEPTION 'Seedling or notification history exists; preserve it before downgrade';
            END IF;
        END $$;
        DROP TABLE mangrovision.email_reminders, mangrovision.staff_notifications,
            mangrovision.activity_logs;
        ALTER TABLE mangrovision.planting_events
            DROP CONSTRAINT ck_lgu_direct_actor,
            DROP COLUMN planted_by_user_id,
            DROP COLUMN initial_height_cm,
            DROP COLUMN initial_condition,
            DROP COLUMN initial_notes;
    """)
