"""Add LIKE public requests without changing existing schedule behavior."""

from alembic import op

revision = '20261006_0013'
down_revision = '20261004_0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute("SET LOCAL statement_timeout = '60s'")
    op.execute("""
        ALTER TABLE mangrovision.planting_schedules
            ADD COLUMN source TEXT NOT NULL DEFAULT 'staff'
            CHECK (source IN ('staff', 'website'));
        CREATE TABLE mangrovision.like_appointment_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference TEXT NOT NULL UNIQUE,
            submission_key UUID NOT NULL UNIQUE,
            payload_hash TEXT NOT NULL,
            organization TEXT NOT NULL,
            contact_name TEXT NOT NULL,
            phone TEXT NOT NULL,
            email TEXT,
            title TEXT NOT NULL,
            start_at TIMESTAMPTZ NOT NULL,
            end_at TIMESTAMPTZ NOT NULL CHECK (end_at > start_at),
            participants INTEGER NOT NULL CHECK (participants BETWEEN 1 AND 10000),
            notes TEXT,
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'confirmed', 'declined', 'cancelled')),
            schedule_id BIGINT UNIQUE REFERENCES mangrovision.planting_schedules(id) ON DELETE SET NULL,
            decision_notes TEXT,
            contacted BOOLEAN NOT NULL DEFAULT FALSE,
            reviewed_by_user_id BIGINT REFERENCES mangrovision.users(id) ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed_at TIMESTAMPTZ
        );
        CREATE INDEX idx_like_requests_status_created
            ON mangrovision.like_appointment_requests(status, created_at DESC);
        CREATE INDEX idx_like_requests_reviewer
            ON mangrovision.like_appointment_requests(reviewed_by_user_id);
        CREATE TABLE mangrovision.like_appointment_rate_limits (
            bucket_key TEXT PRIMARY KEY,
            window_start TIMESTAMPTZ NOT NULL,
            attempts INTEGER NOT NULL CHECK (attempts > 0)
        );
        CREATE INDEX idx_like_rate_window ON mangrovision.like_appointment_rate_limits(window_start);
        ALTER TABLE mangrovision.like_appointment_requests ENABLE ROW LEVEL SECURITY;
        ALTER TABLE mangrovision.like_appointment_rate_limits ENABLE ROW LEVEL SECURITY;
        REVOKE ALL ON mangrovision.like_appointment_requests, mangrovision.like_appointment_rate_limits FROM PUBLIC;
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mangrovision') THEN
                GRANT SELECT, INSERT, UPDATE ON mangrovision.like_appointment_requests TO mangrovision;
                GRANT SELECT, INSERT, UPDATE, DELETE ON mangrovision.like_appointment_rate_limits TO mangrovision;
                GRANT USAGE, SELECT ON SEQUENCE mangrovision.like_appointment_requests_id_seq TO mangrovision;
                CREATE POLICY like_requests_backend ON mangrovision.like_appointment_requests TO mangrovision
                    USING (true) WITH CHECK (true);
                CREATE POLICY like_limits_backend ON mangrovision.like_appointment_rate_limits TO mangrovision
                    USING (true) WITH CHECK (true);
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                REVOKE ALL ON mangrovision.like_appointment_requests, mangrovision.like_appointment_rate_limits FROM anon;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                REVOKE ALL ON mangrovision.like_appointment_requests, mangrovision.like_appointment_rate_limits FROM authenticated;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    op.execute('DROP TABLE mangrovision.like_appointment_rate_limits')
    op.execute('DROP TABLE mangrovision.like_appointment_requests')
    op.execute('ALTER TABLE mangrovision.planting_schedules DROP COLUMN source')
