"""Locate reported deaths and preserve planting history through replacements."""
from alembic import op

revision = '20260916_0008'
down_revision = '20260916_0007'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute("SET LOCAL statement_timeout = '60s'")
    op.execute('''
        ALTER TABLE mangrovision.organization_monitoring_records
            ADD COLUMN location_version INTEGER NOT NULL DEFAULT 0,
            ADD COLUMN location_death_count INTEGER CHECK (location_death_count >= 0);
        WITH previous AS (
            SELECT id, COALESCE(LAG(dead_count) OVER w, 0) AS previous_dead,
                COALESCE(MAX(dead_count) OVER (PARTITION BY organization_id ORDER BY monitored_at, id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0) AS previous_max
            FROM mangrovision.organization_monitoring_records
            WINDOW w AS (PARTITION BY organization_id ORDER BY monitored_at, id)
        ) UPDATE mangrovision.organization_monitoring_records r SET location_death_count =
            COALESCE(r.new_dead_count, CASE WHEN p.previous_dead = p.previous_max
                AND r.dead_count >= p.previous_max THEN r.dead_count - p.previous_max END)
            FROM previous p WHERE p.id = r.id;
        ALTER TABLE mangrovision.planter_assignment_points ADD COLUMN released_at TIMESTAMPTZ,
            ADD COLUMN released_by BIGINT REFERENCES mangrovision.users(id);
        CREATE UNIQUE INDEX uq_death_per_planting_event ON mangrovision.point_death_records(planting_event_id)
            WHERE planting_event_id IS NOT NULL;
        ALTER TABLE mangrovision.planting_events ADD COLUMN replaces_event_id BIGINT
            REFERENCES mangrovision.planting_events(id) ON DELETE RESTRICT;
        CREATE UNIQUE INDEX uq_replacement_event ON mangrovision.planting_events(replaces_event_id)
            WHERE replaces_event_id IS NOT NULL;
        CREATE TABLE mangrovision.monitoring_death_locations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            record_id BIGINT NOT NULL REFERENCES mangrovision.organization_monitoring_records(id) ON DELETE RESTRICT,
            planting_event_id BIGINT NOT NULL REFERENCES mangrovision.planting_events(id) ON DELETE RESTRICT,
            death_record_id BIGINT REFERENCES mangrovision.point_death_records(id) ON DELETE SET NULL,
            created_death BOOLEAN NOT NULL DEFAULT FALSE,
            snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_by BIGINT REFERENCES mangrovision.users(id),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            revoked_at TIMESTAMPTZ,
            revoked_by BIGINT REFERENCES mangrovision.users(id),
            correction_note TEXT
        );
        CREATE INDEX idx_death_locations_record ON mangrovision.monitoring_death_locations(record_id);
        CREATE INDEX idx_death_locations_death ON mangrovision.monitoring_death_locations(death_record_id);
        CREATE UNIQUE INDEX uq_active_death_location ON mangrovision.monitoring_death_locations(planting_event_id)
            WHERE revoked_at IS NULL;
        CREATE TABLE mangrovision.replanting_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            planting_event_id BIGINT NOT NULL UNIQUE REFERENCES mangrovision.planting_events(id) ON DELETE RESTRICT,
            approved_by BIGINT NOT NULL REFERENCES mangrovision.users(id),
            approved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            assignment_id BIGINT REFERENCES mangrovision.planter_assignments(id) ON DELETE RESTRICT,
            replacement_event_id BIGINT UNIQUE REFERENCES mangrovision.planting_events(id) ON DELETE RESTRICT,
            version INTEGER NOT NULL DEFAULT 1
        );
        CREATE INDEX idx_replanting_assignment ON mangrovision.replanting_requests(assignment_id);
        CREATE OR REPLACE FUNCTION mangrovision.link_replacement_event() RETURNS trigger
        LANGUAGE plpgsql SET search_path = mangrovision, extensions, pg_catalog AS $fn$
        BEGIN
            SELECT r.planting_event_id INTO NEW.replaces_event_id
                FROM replanting_requests r JOIN planting_events previous_event ON previous_event.id = r.planting_event_id
                WHERE r.assignment_id = NEW.assignment_id AND previous_event.planting_point_id = NEW.planting_point_id
                AND r.replacement_event_id IS NULL FOR UPDATE OF r;
            RETURN NEW;
        END $fn$;
        CREATE TRIGGER trg_link_replacement_event BEFORE INSERT ON mangrovision.planting_events
            FOR EACH ROW EXECUTE FUNCTION mangrovision.link_replacement_event();
        CREATE OR REPLACE FUNCTION mangrovision.finish_replacement_event() RETURNS trigger
        LANGUAGE plpgsql SET search_path = mangrovision, extensions, pg_catalog AS $fn$
        BEGIN
            IF NEW.replaces_event_id IS NOT NULL THEN
                UPDATE replanting_requests SET replacement_event_id = NEW.id, version = version + 1
                    WHERE planting_event_id = NEW.replaces_event_id;
            END IF;
            RETURN NEW;
        END $fn$;
        CREATE TRIGGER trg_finish_replacement_event AFTER INSERT ON mangrovision.planting_events
            FOR EACH ROW EXECUTE FUNCTION mangrovision.finish_replacement_event();
        REVOKE ALL ON FUNCTION mangrovision.link_replacement_event() FROM PUBLIC;
        REVOKE ALL ON FUNCTION mangrovision.finish_replacement_event() FROM PUBLIC;
        REVOKE ALL ON mangrovision.monitoring_death_locations, mangrovision.replanting_requests FROM PUBLIC;
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mangrovision') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON mangrovision.monitoring_death_locations,
                    mangrovision.replanting_requests TO mangrovision;
                GRANT USAGE, SELECT ON SEQUENCE mangrovision.monitoring_death_locations_id_seq,
                    mangrovision.replanting_requests_id_seq TO mangrovision;
            END IF;
        END $$;
    ''')


def downgrade():
    op.execute('''DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM mangrovision.monitoring_death_locations)
            OR EXISTS (SELECT 1 FROM mangrovision.replanting_requests) THEN
            RAISE EXCEPTION 'Location and replacement history exists; preserve it before downgrade';
        END IF;
    END $$;
    DROP TRIGGER trg_finish_replacement_event ON mangrovision.planting_events;
    DROP TRIGGER trg_link_replacement_event ON mangrovision.planting_events;
    DROP FUNCTION mangrovision.finish_replacement_event();
    DROP FUNCTION mangrovision.link_replacement_event();
    DROP TABLE mangrovision.replanting_requests, mangrovision.monitoring_death_locations;
    ALTER TABLE mangrovision.planting_events DROP COLUMN replaces_event_id;
    DROP INDEX mangrovision.uq_death_per_planting_event;
    ALTER TABLE mangrovision.planter_assignment_points DROP COLUMN released_at, DROP COLUMN released_by;
    ALTER TABLE mangrovision.organization_monitoring_records DROP COLUMN location_version,
        DROP COLUMN location_death_count;
    ''')
