"""Appointment types and a private, durable confirmation-email queue."""

from alembic import op

revision = '20261007_0014'
down_revision = '20261006_0013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '5s'")
    op.execute("SET LOCAL statement_timeout = '60s'")
    op.execute("""
        ALTER TABLE mangrovision.like_appointment_requests
            ADD COLUMN appointment_type TEXT NOT NULL DEFAULT 'tree_planting'
            CHECK (appointment_type IN ('field_visit', 'clean_up_drive', 'tree_planting'));
        ALTER TABLE mangrovision.planting_schedules
            ADD COLUMN appointment_type TEXT NOT NULL DEFAULT 'tree_planting'
            CHECK (appointment_type IN ('field_visit', 'clean_up_drive', 'tree_planting'));
        CREATE TABLE mangrovision.like_appointment_emails (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            request_id BIGINT NOT NULL UNIQUE REFERENCES mangrovision.like_appointment_requests(id) ON DELETE CASCADE,
            recipient_email TEXT NOT NULL,
            encrypted_message TEXT,
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent')),
            attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
            next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            claimed_at TIMESTAMPTZ,
            claim_token UUID,
            sent_at TIMESTAMPTZ,
            last_error TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX idx_like_emails_waiting ON mangrovision.like_appointment_emails(next_attempt_at, id)
            WHERE status <> 'sent';
        ALTER TABLE mangrovision.like_appointment_emails ENABLE ROW LEVEL SECURITY;
        REVOKE ALL ON mangrovision.like_appointment_emails FROM PUBLIC;
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mangrovision') THEN
                GRANT SELECT, INSERT, UPDATE ON mangrovision.like_appointment_emails TO mangrovision;
                GRANT USAGE, SELECT ON SEQUENCE mangrovision.like_appointment_emails_id_seq TO mangrovision;
                CREATE POLICY like_emails_backend ON mangrovision.like_appointment_emails TO mangrovision
                    USING (true) WITH CHECK (true);
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                REVOKE ALL ON mangrovision.like_appointment_emails FROM anon;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                REVOKE ALL ON mangrovision.like_appointment_emails FROM authenticated;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    op.execute('DROP TABLE mangrovision.like_appointment_emails')
    op.execute('ALTER TABLE mangrovision.planting_schedules DROP COLUMN appointment_type')
    op.execute('ALTER TABLE mangrovision.like_appointment_requests DROP COLUMN appointment_type')
